export const GET_DATA_REQ = "GET_DATA_REQ";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const SORT_DATA = "SORT_DATA";

export const GET_CLICKED_DATA_REQ = "GET_CLICKED_DATA_REQ";
export const GET_CLICKED_DATA_SUCCESS = "GET_CLICKED_DATA_SUCCESS";
export const GET_CLICKED_DATA_FAILURE = "GET_CLICKED_DATA_FAILURE";
