export const GET_PROD_REQ = "GET_PROD_REQ";

export const GET_PROD_SUCCESS = "GET_PROD_SUCCESS";

export const GET_PROD_FAILURE = "GET_PROD_FAILURE";

export const GET_PRODUCTS_DATA = "GET_PRODUCTS_DATA";

export const SORT_PRODUCTS = "SORT_PRODUCTS";

